-- testing db and table creation
-- DROP DATABASE IF EXISTS screwit-db
-- CREATE DATABASE screwit-db

-- drops old test tables
DROP TABLE IF EXISTS HIGH_SCORES;
DROP TABLE IF EXISTS ACCOUNT_INFO;

-- create new test tables
CREATE TABLE HIGH_SCORES
    (ID NUMERIC PRIMARY KEY,
     USERNAME VARCHAR(255),
     SCORE NUMERIC);

CREATE TABLE ACCOUNT_INFO
    (ID NUMERIC PRIMARY KEY,
     USERNAME VARCHAR(255),
     PWORD VARCHAR(255));

-- test inserts
INSERT INTO HIGH_SCORES VALUES
    (1,'zach44',444);
INSERT INTO HIGH_SCORES VALUES
    (2,'jerry11',199);
INSERT INTO HIGH_SCORES VALUES
    (3,'beth99',345);

INSERT INTO ACCOUNT_INFO VALUES
    (1,'zach44','qWeR1');
INSERT INTO ACCOUNT_INFO VALUES
    (2,'jerry11','SfA4');
INSERT INTO ACCOUNT_INFO VALUES
    (3,'beth99','dOOjl9');